### ISSUE TITLE
ember-cli-update global command failing on OS X

### ISSUE THREAD

**Issue by kategengler** [kellyselden/ember-cli-update#105]
Caused by line endings. 

I found https://github.com/ember-cli/ember-cli/issues/5342 and it looks like the exact same problem (and modifying line endings in the ember-cli-update bin fixed the problem for me)

**Comment by kellyselden** [comment]
Which version are you running? This was a problem a few versions back, but I switch to Travis CI publishes so it shouldn't be a problem anymore. I just tested v0.6.4, and it works for me.

**Comment by kategengler** [comment]
I had installed, seen 'Installed 0.6.4', but it was a trick; when I looked at package.json for the installed version it was very old. Sorry!
