### ISSUE TITLE
Doesn't work when ember project is subfolder

### ISSUE THREAD

**Issue by boyanyordanov** [kellyselden/ember-cli-update#111]
When I run `ember update` I get this output: 

```
Cloning into bare repository '/var/folders/3s/kt39dyns0ngc361qvkxznlfw0000gn/T/tmp-138173bpZj5aJOoJI/.git'...
Switched to a new branch 'd3bc36e0-939f-11e7-bc82-799873862e5d'
Note: checking out 'ac5673b56583dfee01ceae3783467e5ca4dac25c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ac5673b... 2.7.0
File: /bin/sh
Command failed: git commit -m "diff"

Error: Command failed: git commit -m "diff"

    at checkExecSyncError (child_process.js:472:13)
    at Object.execSync (child_process.js:512:13)
    at run (/<path-to-app>/node_modules/ember-cli-update/node_modules/git-diff-apply/src/run.js:8:19)
    at ncp.then.err (/<path-to-app>/node_modules/ember-cli-update/node_modules/git-diff-apply/src/index.js:62:5)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Oddly it can't commit this for some reason, but there is another commit preceding the error. 

I can only think of two possible reasons for the failed update at this moment: 

1. Our project is at Ember 2.7 right now. Perhaps it's too old for the tool to work with?
2. The app is inside a directory in a bigger git repository, which might prevent the underlying tools to do their git magic?

It also fails if I run the global `ember-cli-update` with the same error and slightly bigger output containing information about the system.

Please let me know if this is a valid issue and if I can assist further.

**Comment by boyanyordanov** [comment]
Seems like the reason for the failed run is indeed the directory structure. After I copied out the ember app and initialized a new repository. 

The command was able to run and finish. I guess I'll look at this as a two step precess and transfer the changes to the actual repo.

**Comment by kellyselden** [comment]
We might be able to fix this. Is your Ember app a git submodule of the parent?

**Comment by boyanyordanov** [comment]
Thanks for the quick reply. Not a submodule, just regular directory inside the parent. And the git repository is in the parent.

**Comment by kellyselden** [comment]
Hmm I'm not family with that kind of setup. Can you explain a bit about your workflow? When you make an Ember change, where do do you run the git commands to commit? and what is the affect on the parent.

From the error message, it looks like running `git commit` in your ember app's dir is hard erroring, so I wonder how you are actually committing your Ember changes without error.

**Comment by boyanyordanov** [comment]
It seemed like a good idea at the time to keep the ember app and the backend in the same repository. 

Structure looks similar to this : 
```
- .git
- app <-backend code 
- <other directories>
- public <- web entry point
- ember-app-dir 
... more files
```

I've had no trouble commiting code via the command line either from the directory with the ember app or from the root. It all goes in the same repository. 

And I have made changes to the build config, so that ember uses `public` as `dist` and we can deploy the app all at once and have the backend framework serve `index.html` and the ember app on initial load. 

It's a bit of a weird setup and I'll absolutely understand if you don't want to support anything like this, since it's also not recommended by ember.

**Comment by kellyselden** [comment]
OK. Did you retain the `.git` folder that came with the Ember app, or is that gone?

**Comment by boyanyordanov** [comment]
It's gone. I can't remember doing it but I probably removed it in the beginning.

**Comment by kellyselden** [comment]
OK. I think we can fix this. Don't know the best way yet though. Might be to run the global at your git dir and `ember-cli-update --path ember-app-dir` or maybe if you are running it as a command `ember update --path ..`.

**Comment by boyanyordanov** [comment]
I will try that and report. Didn't know about this option.

**Comment by kellyselden** [comment]
They don't exist yet, I'm just brainstorming possible solutions :)

**Comment by boyanyordanov** [comment]
Alright. I can try to dig in and see if I can get it to work.

**Comment by mjuniper** [comment]
We have a similarly non-standard directory structure. I haven't tried this tool yet but I hope to soon and, based on this issue, I suspect it will currently not work. We have a monorepo setup with lerna and the directory structure looks like this:

- .git
- packages
  - ember addon
  - ember addon 2
  - ember app
  - ember app 2
... other files

**Comment by ro0gr** [comment]
> Might be to run the global at your git dir and ember-cli-update --path ember-app-dir or maybe if you are running it as a command ember update --path ...

What if update command will auto-detect the nearest ember project from the current directory(where the command launched)? 
I think it's an expected behavior for most of users.
Also it doesn't need any special API.

**Comment by ro0gr** [comment]
By nearest I mean something like ember-cli/lib/models/project#closestSync(sorry, can't provide a direct link from mobile)

**Comment by boyanyordanov** [comment]
The workaround for us was: 

1. copy the ember app out of the big repo
2. init a new git repo in the copy
3. run ember-cli-update
4. resolve any conflicts / finish the update process 
5. replace the app in the big repo 

So far it has worked good enough.

**Comment by kellyselden** [comment]
So this is a really difficult problem. The current process fundamentally doesn't work for subfolders. I generate a git patch with the project at root, and then expect to apply the patch to another project at root. If the project is in a subfolder, git can't apply the patch. My first attempt is in https://github.com/kellyselden/ember-cli-update/tree/subfolder, but it doesn't look like it will work.

**Comment by kellyselden** [comment]
Coming in https://github.com/kellyselden/git-diff-apply/pull/112.

**Comment by kellyselden** [comment]
Released in v0.9.0!

**Comment by boyanyordanov** [comment]
Amazing work! Thanks a lot! I will try to test it this week or next week.

**Comment by joegaudet** [comment]
@kellyselden I'm still seeing this happen using the latest version of the ember-cli-update, is there something I'm supposed to do to properly update a nested ember app?

**Comment by kellyselden** [comment]
@joegaudet You'll probably want to file a new issue with as much info as you can.
