### ISSUE TITLE
Getting 'You must start with a clean working directory'

### ISSUE THREAD

**Issue by alexandremjacques** [kellyselden/ember-cli-update#119]
Hi,

Trying to update a Ember 2.14 project to Ember 2.15, I'm receiving a 'You must start with a clean working directory'

```
ember-cli: 2.15.0
node: 8.4.0
npm: 5.3.0
git: 2.14.1
os: darwin x64
```

If you need any more info, feel free to contact me.

Cheers!

**Comment by kellyselden** [comment]
It looks from your versions that you are already running ember-cli 2.15. Was your working directory clean? What is the output of running `git status`? Can you try running this command `DEBUG=ember-cli-update,git-diff-apply ember-cli-update` and post the output? What version of `ember-cli-update` are you using?

**Comment by kellyselden** [comment]
Are you running as a global executable or an ember-cli command?

**Comment by kellyselden** [comment]
Closing for now, let me know if it is still an issue in the latest version.
