### ISSUE TITLE
Manually Resolve Conflicts (without a difftool)

### ISSUE THREAD

**Issue by caseywatts** [kellyselden/ember-cli-update#154]
Hi!

I'd love to use this tool while using my normal merge conflict resolution workflow. I usually use atom to resolve merge conflicts - it has (non-difftool) diff resolution capabilities built into it.

1. If I [cmd+c] during the difftool steps, would I be missing any steps that come after?
2. Is this project set up in a way that we could disable running the difftool using a flag like `--disable-difftool` or something?

**Comment by rwjblue** [comment]
I think you are basically asking for https://github.com/kellyselden/ember-cli-update/pull/57 (`--ignore-conflicts`).

**Comment by caseywatts** [comment]
that's just what I want!
I'd skimmed over that in the table more than once - I was looking specifically for `difftool`.

Made a PR to clarify the README for someone like me:
https://github.com/kellyselden/ember-cli-update/pull/155
