### ISSUE TITLE
Auto-running Codemods

### ISSUE THREAD

**Issue by caseywatts** [kellyselden/ember-cli-update#156]
I just used this tool to update my codebase and I liked it a lot! much better than doing `ember init` after manually updating 🎉 

The auto-running codemod step made this interesting. I wanted to commit the [ember file changes] (like a default comment in `environment.js`) separately from the [ember modules codemod changes], but since this tool automatically did both at once they ended up in the same commit. I'm just accepting them in the same commit for now, but I can imagine some ways this would run better for others / in the future.

Ideas:
- After doing the ember file changes, suggesting something like `you should run "npx ember-modules-codemod" now to get these updated` instead of doing it automatically
- Commiting the ember changes first, and then auto-running the codemod after
- introducing a flag to NOT auto-run any codemods?
- saying in the readme more clearly that some codemods ARE auto-run - and for which versions etc (currently it's only listed as a possibility under "future ideas")

**Comment by rwjblue** [comment]
> introducing a flag to NOT auto-run any codemods?

We should definitely do this regardless of the rest...

**Comment by rwjblue** [comment]
@caseywatts - Thanks for opening this up! I definitely agree that its nice to have separate more focused commits (which assist in bisecting and whatnot going forward).

**Comment by kellyselden** [comment]
How do we want to expose this? The problem with breaking it into two and having `ember update --no-codemods` and `ember update --only-codemods` is by the second command, you've lost the auto-detection of your previous version. You've now updated to > 2.16, so the codemod doesn't know to run.

**Comment by caseywatts** [comment]
What is the version change information used for?

- only to determine whether or not to run the codemod?
- or also for some configuration in how the codemod gets run?

**Comment by kellyselden** [comment]
The first one.

**Comment by ro0gr** [comment]
What if we run codemod regardless of `from` and `to`? 
As far as I understand it should not matter how many times we ran codemod, the output should be stable.

**Comment by rwjblue** [comment]
True.  We could also emit the command line invocation for the follow up (or write it to some well known `tmp/` path or other trickery...)...
