### ISSUE TITLE
path option is not in docs

### ISSUE THREAD

**Issue by brandonjmckay** [kellyselden/ember-cli-update#211]
https://github.com/kellyselden/ember-cli-update/issues/111 mentions that a new helper has been added for when using the update command on mono-repos.

I tried using `ember update --help`, but it does not mention this new method.

I believe the `--path` option was added, but am just in the middle of trying it out.

**Comment by kellyselden** [comment]
That was just brainstorming. I believe I was able to accomplish it without any new options. Just run the command in your ember folder.
