### ISSUE TITLE
Removes all other node_modules folders

### ISSUE THREAD

**Issue by knownasilya** [kellyselden/ember-cli-update#212]
My Ember app is in a "mono-repo", so the top folder is the git repo, and has a couple Ember apps and an Express app. I ran this update in one of the Ember apps, and all of the other `node_modules` folders are gone. In the other Ember apps and in the top level folder. As well as in an engine inside of one of the Ember apps.

**Comment by kellyselden** [comment]
This might be related to #143, where we are trying to track it down.

**Comment by kellyselden** [comment]
Going to close because I'm pretty sure #143 encompasses this.
