### ISSUE TITLE
ember-cli blueprints do not pin version of ember-cli but we should

### ISSUE THREAD

**Issue by Gaurav0** [kellyselden/ember-cli-update#216]
In `package.json`

You will see `"ember-cli": "~2.17.0"` in `devDependencies` hash for example.

Users of this addon probably do **not** want to upgrade ember-cli automatically with `npm install` or `yarn upgrade`.

We should automatically remove the `~`.

Perhaps instead get a message that a new version is available and you can run `ember update`. (not sure under what conditions exactly, we can discuss.)

This does not apply to `ember-source` or `ember-data`.

**Comment by kellyselden** [comment]
We've discussed this in ember-cli before. We feel that users getting hotfixes of stable ember-cli versions WITHOUT any associated blueprint updates is better than pinning them with the buggy version.
