### ISSUE TITLE
Add bower to devDependencies when needed?

### ISSUE THREAD

**Issue by jacobq** [kellyselden/ember-cli-update#257]
I don't have very good steps for demonstrating this, so feel free to close if you see fit, but I think I found a potential bug. We were [trying to update `ember-localstorage-adapter`](https://github.com/locks/ember-localstorage-adapter/pull/223) to [eliminate some deprecation warnings](https://github.com/locks/ember-localstorage-adapter/issues/221). For the most part, `ember-cli-update` seems to have worked OK, except for two details:

1. The project contained a `bower.json` (though it did not have any dependencies in it) that caused problems when `ember-try` ran. It seems that this file should have been removed (or perhaps `bower` should have been added to `devDependencies`).

2. The project contained a `testem.json` that I think [came from ember-cli](https://github.com/locks/ember-localstorage-adapter/commit/0e1950692b3a886760c8dc745990d90c9f0f3371#diff-8ee23fdeee2ec605a1e96a91991b764e) and a `testem.js` that I suspect [was added by mistake](https://github.com/locks/ember-localstorage-adapter/commit/7019c18fe2d6ba27fc5c2a1b17c0f4b24f01f2e3#diff-1a0ca09a3f8c753c31615ee16e6199ee). In any case, `ember-cli-update` seems to have updated the `testem.js` file (e.g. to use headless Chrome) meanwhile the `testem.json` still referenced PhantomJS and seemed to take precedence. I'm not sure if this is `ember-cli-update`'s fault or not, but perhaps it's a "gotcha" to check for?

(incomplete attempt at reproducing problem shown below)
<summary><details>

* `npm install -g ember-cli@2.7` (newer versions might also work -- not sure when the bower change happened)
* `npm install -g phantomjs` ()

```
$ ember -v
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.7.0
node: 4.8.7
os: linux x64
```

* `ember addon my-addon`
* `cd my-addon`
* `npm test` # Thought this would pass but got stuck here so abandoned trying to make repro steps
* `npm install ember-cli-update`
...

</details></summary>

**Comment by kellyselden** [comment]
This project applies a changeset between your current ember-cli version and the latest. Since bower.json wasn't changed between those versions (it doesn't exist), it was untouched. bower.json was removed  from ember-cli's blueprint a while ago, before your starting point.

You can set the --to option to a further back version to get more changes in your update, or you can use the --reset option to get rid of old files.

Feel free to submit a PR to the README if any of this is more clear than what's already in there.

cc @locks

**Comment by jacobq** [comment]
Thanks for the explanation; for the most part that makes sense. I see why this tool wouldn't have removed it, but what surprised me was that it caused a problem (`ember try:one ember-default` generates an error `Error: Cannot find module 'bower'...` unless one does `npm install --save-dev bower`, which I didn't think used to happen). I guess I would need to get a better understanding regarding the interaction between ember-cli and bower to understand why.

**Comment by kellyselden** [comment]
It might even be an ember-try issue, not sure.
