### ISSUE TITLE
Flesh out README a bit more.

### ISSUE THREAD

**Issue by rwjblue** [kellyselden/ember-cli-update#58]
- [x] Add more information to the summary section.  I'd like to generally explain what we are doing (e.g. creating a diff between the ember-cli blueprint output of the `--from` version to the `--to` version, and then applying that diff to their project).
- [x] Explain the end / conflict workflow (aka lots of links about `git mergetool`).
- [x] Update error message (and link back to our README?) for dirty working directory (see https://github.com/kellyselden/ember-cli-update/issues/64).

**Comment by rwjblue** [comment]
FYI - I added the following to the list in the description:

> Update error message (and link back to our README?) for dirty working directory (see https://github.com/kellyselden/ember-cli-update/issues/64).

**Comment by kellyselden** [comment]
I think everything is covered here.
