### ISSUE TITLE
Unable to run `ember update`

### ISSUE THREAD

**Issue by jakedetels** [kellyselden/ember-cli-update#64]
After installing the addon globally and then running `ember update`, I get the error `The specified command update is invalid.`

Additionally, after installing the addon within an Ember project directory (with `ember install ember-cli-update`) followed by running `ember-cli-update`, I get the error: `(node:9836) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): You must start with a clean working directory`.

Below is my console history while installing the addon globally and then trying to run `ember update`.
```
C:\Users\jdetels
λ npm -v
5.3.0

C:\Users\jdetels
λ npm install -g ember-cli-update
C:\Users\jdetels\AppData\Roaming\npm\ember-cli-update -> C:\Users\jdetels\AppData\Roaming\npm\node_modules\ember-cli-update\bin\ember-cli-update.js
+ ember-cli-update@0.6.1
added 77 packages in 11.411s

C:\Users\jdetels
λ ember -v
ember-cli: 2.14.1
node: 6.11.2
os: win32 x64

C:\Users\jdetels
λ ember update
The specified command update is invalid. For available options, see `ember help`.
```

**Comment by rwjblue** [comment]
> After installing the addon globally and then running ember update, I get the error The specified command update is invalid.

The command to run is `ember-cli-update` (not `ember update`).

**Comment by jakedetels** [comment]
@rwjblue: The README says the following:

> Inside your project directory, either run
> `ember-cli-update`
> for global or
> `ember update`
> as an Ember CLI command.

I interpret this to mean that we can use `ember-cli-update` (if we've already installed ember-cli-update globally via `npm i -g ember-cli-update`) or use `ember update` (if we've only installed ember-cli-update locally in a project using `ember install ember-cli-update`).  Is this correct?

When inside a project directory (and after having installed ember-cli-update both globally and locally), I get similar results when trying to use either `ember-cli-update` or `ember update`:

When running `ember-cli-update` from a project directory, I get the response:
> (node:8700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): You must start with a clean working directory

When running `ember update` from a project directory, I get the response:
> You must start with a clean working directory

What does it mean here to "start with a clean working directory"?

**Comment by rwjblue** [comment]
Ahh.  Sorry about that!  I missed that addition 😸 .

> I interpret this to mean that we can use ember-cli-update (if we've already installed ember-cli-update globally via npm i -g ember-cli-update) or use ember update (if we've only installed ember-cli-update locally in a project using ember install ember-cli-update). Is this correct?

Yes, if you want to use `ember update` you would have to install `ember-cli-update` inside the project (aka not globally).

> What does it mean here to "start with a clean working directory"?

This tool uses `git` to apply a patch to your project, it checks `git status` before running to ensure that there are no uncommited changes before running.  A "clean working directory" generally means `git status` shows nothing.

You can see [the rejection comes from here](https://github.com/kellyselden/git-diff-apply/blob/master/src/index.js#L23-L25), and the `isGitClean()` function is essentially using regexps ([here](https://github.com/kellyselden/git-diff-apply/blob/master/src/is-git-clean.js))  to determine if it is clean or dirty.

Can you share the output of `git status` in your project so that we can see why the regexp's don't match?

**Comment by jakedetels** [comment]
Mystery solved - after committing my most recent changes, `ember update` worked as described in the docs.  Thanks for the help, @rwjblue .

**Comment by kellyselden** [comment]
Thank you @jakedetels for all the troubleshooting info. I can see there are a few things you tripped up on that I can account for in the README.

**Comment by mikeelemuel** [comment]
I installed the addon by running this command into may terminal `ember install ember-cli-update` inside my ember project and the message I got from my terminal was 
`npm: Installed ember-cli-update
Installed addon package.`

But then when I run the `ember-cli-update --to 3.4` I received an error called `-bash: ember-cli-update: command not found`
