### ISSUE TITLE
Using --to ~2.12 updates ember-data to ^2.12

### ISSUE THREAD

**Issue by ryanrishi** [kellyselden/ember-cli-update#71]
When running `ember-cli-update --to ~2.12`, ember-data v2.14.10, as `"ember-data": "^2.12.0"` is in package.json. We should apply the `--to` argument to ember-data as well.

**Comment by kellyselden** [comment]
This uses the default blueprints, and you subsequently get any bugs in those templates. Here is what you are getting

https://github.com/ember-cli/ember-new-output/blob/v2.12.3/package.json#L32

So it is working as expected.
