### ISSUE TITLE
You must start with a clean working directory –– but as far as I know it is clean?

### ISSUE THREAD

**Issue by gordonbisnor** [kellyselden/ember-cli-update#80]
I've installed ember update ^0.6.1 as an addon, committed updates to my yarn.lock and package.json files, but now ember update is returning

```bash
You must start with a clean working directory
```

when I run git status I'm seeing:
```bash
On branch master nothing to commit
working directory clean
```

**Comment by kellyselden** [comment]
Hmm. That's a mystery to me. Maybe @rwjblue has an idea. Maybe we want to add an option that opts out of dirty checking while we iron out the kinks of this tool. That way you can still update even though there may be a bug somewhere.

**Comment by gordonbisnor** [comment]
@kellyselden Wondering if this may be somewhat unrelated to ember-cli-update –– I have a Yarn/node/sass issue that I have not yet sorted out where I need to run 

```bash
npm rebuild node-sass
```
 regularly when installing addons – it doesn't affect git status but perhaps it could be affecting ember-cli-update

**Comment by musaffa** [comment]
I've this same problem. Cannot update with `ember update`.

**Comment by gordonbisnor** [comment]
Looks like Git 2.9.1 changed working directory to working tree, so the isGitClean regex is not working for Git < 2.9.1  –– I see that  @rwjblue has already [proposed a change](https://github.com/kellyselden/git-diff-apply/issues/43) to git-diff-apply that looks like it would this.

**Comment by kellyselden** [comment]
OK I'll get that merged in. Thanks for the help.

**Comment by kellyselden** [comment]
Released in v0.6.3

**Comment by alexandremjacques** [comment]
Having this very same issue in 0.6.4 (Git 2.14.1 / Node 8.4.0) trying to migrate Ember 2.14 to 2.15

**Comment by kellyselden** [comment]
@alexandremjacques mind filing a new issue, you might have discovered a new case because the old trigger should have been fixed.
